let json {
    
    tipo_de_registro:'asd',
    proceso:"",
    identificacion_empleador:"",
    periodo_de_la_novedad: "",
    clave_de_nomina: "",
    tipo_de_documento: "",
    numero_de_documento: "",
    nombres: "",
    primer_apellido: "",
    segundo_apellido: "",
    sexo: "",
    salario_isr: "",
    otras_remuneraciones: "",
    identificacion_agente_retencion_isr: "",
    remuneracion_otros_empleados: "",
    ingresos_excento_isr: "",
    salario_cotizable_infotep: "",
    tipo_ingreso: "",
    regalia_pascual: "",
    preaviso_cesntia_viaticos_indemnizaciones: "",
    numero_de_registros: "",
}